spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dataStoragePi
    username : root
    password : davide25
    #password :
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


fileRepoFolder: /home/raspdavide/Desktop/Storage/
#fileRepoFolder:  C:\Users\busad\Desktop